### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns-python#11]
See title. Need to have a python 3 version of this.

Unsure what amount of code changes are required for this, need to investigate

**Comment by pratishrutinayak** [comment]
Checked it using Python 3. 
Working fine. Just had to pip install requests.

**Comment by Dyex719** [comment]
Created a virtualenv and ran `pip install -r requirements.txt`. No errors.

**Comment by rebstar6** [comment]
interesting, thanks @Dyex719 and @pratishrutinayak - will validate and close
