### ISSUE TITLE
Start vinyldns-python client

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns-python#2]
**Background**
We have most of the makings of a good vinyldns python client in the functional tests at https://github.com/vinyldns/vinyldns/blob/master/modules/api/functional_test/vinyldns_python.py

With a little cleanup, this can be moved into the vinyldns-python repository and setup as a first class project.

**Scope of work**
* Port the vinyldns_python.py library to the vinyldns-python repository
* Clean up anything that is not-standard for python
* Add unit tests?  Unclear on how to unit test this, since it is just an API wrapper for vinyldns api.  There seem to be a lot of unit testing API tools out there, would like whoever starts this up to laydown some opinions on the matter.  If not, this looked interesting and it works with pytest which we use for vinyldns - https://github.com/taverntesting/tavern
* Setup a release process (setup.py) to be able to build and release the project to pypi
* Add LICENSE and license headers
* Add a README on usage
* Setup travis

**Comment by acnewberry** [comment]
Great idea
