### ISSUE TITLE
Add ownerGroupId to RecordSet update method

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns-python#36]
In support of the new [shared zones](https://github.com/vinyldns/rfcs/blob/master/text/0002-shared-zones.md) feature coming to VinylDNS we need to add the optional `ownerGroupId` field to the RecordSet update method.

#### Example Request
```
{
  "id": "dd9c1120-0594-4e61-982e-8ddcbc8b2d21",
  "name": "already-exists",
  "type": "A",
  "ttl": 38400,
  "records": [
    {
      "address": "6.5.4.3"
    }
  ],
  "zoneId": "2467dc05-68eb-4498-a9d5-78d24bb0893c",
  "ownerGroupId": "f42385e4-5675-38c0-b42f-64105e743bfe"
}
```

### Additional Information
* Get recordSet first then update
* If ownerGroupId is removed or set to an empty string, the attribute should not be included in the update request.
* If ownerGroupId is not modified from the retrieved recordSet it should be sent in the update.
* If ownerGroupId is modified, send the modification

**Comment by nimaeskandary** [comment]
Not closing this one but pointing out https://github.com/vinyldns/vinyldns-python/pull/45. In additional info it lists `Get recordSet first then update`, but the next steps are pretty much saying to send the update as it is regardless. Is the initial get needed/ can this be closed?
