### ISSUE TITLE
Add support for isTest flag to zone model

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns-python#39]
The API supports an `isTest` flag in the zone connection request (model: https://github.com/vinyldns/vinyldns/blob/1a2d12a7e983a7229aec573a618b275edf1b3343/modules/core/src/main/scala/vinyldns/core/domain/zone/Zone.scala#L114).

The zone model needs to include `isTest` so that `String` serialization prints out this info.

**Comment by nimaeskandary** [comment]
May be able to close this after https://github.com/vinyldns/vinyldns/pull/610
