### ISSUE TITLE
Add environment variable support

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns-python#4]
Right now, to use this client, you have to create a new client:

```
client = VinylDNSClient(url, access_key, secret_key)
zones = client.getZones()
```

It would be nice to allow people to set the environment variables and call getZones (or all the other api functions) directly. This is similar to how the ruby client works (see https://github.com/vinyldns/vinyldns-ruby#requirements)

**Comment by isaac-philip** [comment]
for testing, any dummy values for below ?

1. url
2. access_key
3. secret_key

**Comment by isaac-philip** [comment]
Please allow me to take this one, thanks.

**Comment by rebstar6** [comment]
ahh sorry @isaac-philip, my notifications weren't set properly! :(

there's a bunch more work to be done on this project - we will be making more issues in the next few days, but feel free to reach out to us in gitter (https://gitter.im/vinyldns/Lobby) if youre looking to contribute!

**Comment by isaac-philip** [comment]
Ok no worries. thanks
