### ISSUE TITLE
Add travis build badge to Readme

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns-python#40]
We use Travis CI to build and test the VinylDNS Python client. Adding the Travis badge will quickly indicate that to users and let them know if the master branch is building and passing.

Should be: `[![Travis build](https://api.travis-ci.org/vinyldns/vinyldns-python.svg?branch=master)](https://travis-ci.org/vinyldns/vinyldns-python)`

see the main [VinylDNS Readme](https://github.com/vinyldns/vinyldns/blob/master/README.md) for reference

**Comment by pauljamescleary** [comment]
Sorry, did this, closed
